### PR TITLE
Refactored CLI

### PR DESCRIPTION
**Pull request by garrettluu**
Addresses [this issue](https://github.com/SheetJS/sheetjs/issues/1922).

Moved CLI into a separate package located in `packages/crc32-cli`. Published npm package [here](https://www.npmjs.com/package/crc32-cli).

### CODE REVIEW

**Comment by stof** [comment]
This misses the removal of CLI-only dependencies from the package.json of the crc32 package (which is the main reason for the refactoring)

**Comment by stof** [comment]
@garrettluu @srijonsaha what is the state of this work ?

**Comment by stof** [comment]
@SheetJSDev any news on this ?

**Comment by stof** [comment]
@SheetJSDev any chance to have this merged ? This is the last package where the CLI is not split yet IIRC.

**Comment by SheetJSDev** [comment]
We'll split the difference: keep the bin-script but refactor to remove the dependencies.  The CLI script has been added to the repo in a commit attributed to @garrettluu

**Pull request closed without merging**
